development:
  adapter: postgresql
  encoding: unicode
  database: beauvoir-development
  pool: 5
  username: vagrant
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: beauvoir-test
  pool: 5
  username: vagrant
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: beauvoir-production
  pool: 5
  username: beauvoir
  password:
