default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beauvoir-development
  username: vagrant
  password:

test:
  <<: *default
  database: beauvoir-test
  username: vagrant
  password:

production:
  <<: *default
  database: beauvoir-production
  username: beauvoir
  password: <%= ENV['BEAUVOIR_DATABASE_PASSWORD'] %>
