#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.
begin
  load File.expand_path("../spring", __FILE__)
rescue LoadError
end


APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
# require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
